import numpy as np

import scipy.conftest
import scipy.constants
import scipy.integrate

from particle import PointParticle


class Wire():
    """A straight current-carrying wire with a specified position, length, and resistance.
    """

    def __init__(self, end1: np.ndarray, end2: np.ndarray, resistance: np.float64) -> None:
        """Initiate a an current-carrying wire.

        Parameters
        ----------
        end1 : np.ndarray
            The coordinates of one end of the wire
        end2 : np.ndarray
            The coordinates of the other end of the wire
        resistance : np.float64
            The total resistance of the wire
        """
        self.end1 = end1
        self.end2 = end2
        self.resistance = resistance

    def calculate_length(self) -> np.float64:
        """Calculate the length of the wire.

        Returns
        -------
        np.float64
            A scalar value representing the length of this wire. 
        """
        return np.linalg.norm(self.end2 - self.end1)

    def calculate_electromotive_force(self, particles: list) -> np.float64:
        """Calculate the electromotive force(emf) across the wire from the particle.

        Parameters
        ----------
        particle : PointParticle
            The particle that is exerting a electric field across the wire.

        Returns
        -------
        The difference in electric potential between the ends of the wires.
        """
        # The vector of the space between the wires
        wire_vector = self.end2 - self.end1
        unit_vector = wire_vector / self.get_length()

        def sum_electric_fields(point: np.ndarray) -> np.ndarray:
            """Calculate the net electric field at a given point.

            Parameters
            ----------
            point : np.ndarray
                A 3D vector representing the point to calculate the electric field at.

            Returns
            -------
            np.ndarray
                A 3D vector representing the net electric field in V/m or N/C.
            """
            electric_fields = map(
                lambda particle: particle.electric_field(point), particles
            )
            return sum(electric_fields)

        # Negative integral of the electric field across the wire.
        return -scipy.integrate.quad_vec(
            lambda x: sum_electric_fields(self.end1.point + unit_vector * x),
            0,
            self.get_length()
        )

    def calculate_current(self) -> np.float64:
        """Calculate the current flowing through this wire.

        Returns
        -------
        np.float64
            The current flowing through the wire in amps.
        """
        return self.electromotive_force() / self.resistance

    def calculate_magnetic_field(self, point: np.ndarray) -> np.ndarray:
        """Calculate the magnetic field generated by this wire at a point.

        Parameters
        ----------
        point : np.ndarray
            A 3D vector of np.float64 representing a point to calculate the magnetic field at.

        Returns
        -------
        np.ndarray
            A 3D vector representing the strength of the magnetic field at the point in teslas. 
        """
        def r(l: np.float64) -> np.ndarray:
            """Calculate r, the 3D vector between the point `l` distance away from `self.point1` along the wire and `point`.
        

            Parameters
            ----------
            l : np.float64
                The distance along this wire from `self.point1` in meters.

            Returns
            -------
            np.ndarray
                A 3D the vector between the point `l` distance away from `self.point1` along the wire and `point`.
            """
            wire_vector = self.end2 - self.end1
            unit_vector = wire_vector / self.get_length()
            return point - (self.end1 + l * unit_vector)

        # Biot-Savart law
        return scipy.constants.mu_0 * np.cross(
            self.current(),
            scipy.integrate.quad(
                r() / np.linalg.norm(r()) ** 3,
                0,
                self.get_length()
            )
        ) / 4 * scipy.constants.pi
